version: '3.8'

services:
  be-core-service:
    build:
      context: .
      dockerfile: apps/backends/be-core-service/Dockerfile
    container_name: be-core-service-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # Дополнительные переменные для лучшего hot reload
      - NX_SKIP_NX_CACHE=true
      - NX_DAEMON=false
    working_dir: /app
    restart: unless-stopped
    # Docker Compose Watch конфигурация
    develop:
      watch:
        # Синхронизация исходного кода
        - action: sync
          path: ./apps/backends/be-core-service/src
          target: /app/apps/backends/be-core-service/src
          ignore:
            - "**/*.spec.ts"
            - "**/*.test.ts"
        # Синхронизация библиотек
        - action: sync
          path: ./libs
          target: /app/libs
          ignore:
            - "**/*.spec.ts"
            - "**/*.test.ts"
        # Перезапуск при изменении конфигурационных файлов
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./nx.json
        - action: rebuild
          path: ./apps/backends/be-core-service/project.json
        - action: rebuild
          path: ./apps/backends/be-core-service/webpack.config.js
