version: '3.9'

services:
  be-core-service:
    build:
      context: .  # ← КЛЮЧЕВОЕ ИЗМЕНЕНИЕ: корень Nx-репозитория
      dockerfile: apps/backends/be-core-service/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db  # Запускается после базы данных
    volumes:
      - ./:/workspace           # Подключаем код проекта
      - /workspace/node_modules # Скрываем node_modules, чтобы он не перезаписывался с хоста

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: coredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
