version: '3.8'

services:
  nginx:
    image: 480203687881.dkr.ecr.eu-central-1.amazonaws.com/ewandr/nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"         # прокидываем порт 80 на локалку (можно "8080:80", если 80 занят)
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: core_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      # Персистентное хранение данных
      - postgres_data:/var/lib/postgresql/data
      # Опционально: скрипты инициализации
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d core_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  be-core-service:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_PREFIX}/be-core-service:${BE_CORE_SERVICE_TAG}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Подключение к PostgreSQL
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/core_service_db
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=core_service_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres123
      - DB_SSL=false
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  client-shell:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_PREFIX}/client-shell:${CLIENT_SHELL_TAG}
    ports:
      - "4200:4200"
    depends_on:
      - be-core-service
    environment:
      - NODE_ENV=development
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

# Именованные тома для персистентности данных
volumes:
  postgres_data:
    driver: local
  dist_volume:
#  pgadmin_data:
#    driver: local
