export const mfSharedLibs = [
  '@angular/core',
  '@angular/core/primitives/signals',
  '@angular/common',
  '@angular/common/http',
  '@angular/router',
  '@angular/animations',
  '@angular/cdk',
  '@angular/material',
  '@angular/platform-browser',
  'rxjs',
  'rxjs/operators',
  '@angular/core/primitives/di',
  '@apollo/client/core',
  '@apollo/client/link/batch',
  '@apollo/client/link/error',
  '@apollo/client/dev',
];
